In [20]:
import pandas as pd
import sqlalchemy as db
from tqdm import tqdm

In [2]:
def pivot_table(df):
    p = df.pivot(index='X', columns='DataSet', values='Y')
    return p

In [11]:
username = 'amos'
password = 'M0$hicat'
host = '192.168.0.131'
port = '3306'
database = 'civDW'
connection_string = connection_string = f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}'
conn = db.create_engine(connection_string)

In [4]:
query = """
    SELECT 
        PLAYERS.`PlayerObjectId`,
        `PLAYERS`.`CivilizationName`,
        `PLAYERS`.`LeaderName`,
        `PLAYERS`.`GameId`,
        c.`DataSet`,
        c.`DataSetId`,
        c.`ObjectId`,
        c.X,
        c.Y
    FROM civDW.`Players` AS PLAYERS
    INNER JOIN (
        SELECT 
            b.*,
            a.`DataSet`,
            a.`ObjectId`
        FROM civ.`DataSets` AS a
        INNER JOIN civ.`DataSetValues` AS b 
            ON a.`DataSetId` = b.`DataSetId`
    ) c
    ON c.`ObjectId` = PLAYERS.`PlayerObjectId`
    WHERE c.DataSet IN ('Gold', 'Science', 'Faith', 'Culture')
"""
df = pd.read_sql_query(query, conn)
df.head()

,PlayerObjectId,CivilizationName,LeaderName,GameId,DataSet,DataSetId,ObjectId,X,Y
0,1,Scotland,Robert the Bruce,1,Gold,1,1,1,5.0
1,1,Scotland,Robert the Bruce,1,Gold,1,1,3,10.0
2,1,Scotland,Robert the Bruce,1,Gold,1,1,4,15.0
3,1,Scotland,Robert the Bruce,1,Gold,1,1,5,20.0
4,1,Scotland,Robert the Bruce,1,Gold,1,1,6,25.0

In [5]:
slice = df[(df['PlayerObjectId'] == 1) &
           (df['GameId'] == 1)]
slice

,PlayerObjectId,CivilizationName,LeaderName,GameId,DataSet,DataSetId,ObjectId,X,Y
0,1,Scotland,Robert the Bruce,1,Gold,1,1,1,5.0
1,1,Scotland,Robert the Bruce,1,Gold,1,1,3,10.0
2,1,Scotland,Robert the Bruce,1,Gold,1,1,4,15.0
3,1,Scotland,Robert the Bruce,1,Gold,1,1,5,20.0
4,1,Scotland,Robert the Bruce,1,Gold,1,1,6,25.0
...,...,...,...,...,...,...,...,...,...
348,1,Scotland,Robert the Bruce,1,Faith,4,1,117,33.0
349,1,Scotland,Robert the Bruce,1,Faith,4,1,120,38.0
350,1,Scotland,Robert the Bruce,1,Faith,4,1,123,40.0
351,1,Scotland,Robert the Bruce,1,Faith,4,1,129,39.0
352,1,Scotland,Robert the Bruce,1,Faith,4,1,130,NaN

In [6]:
p = slice.pivot(index='X', columns='DataSet', values='Y')
p

DataSet  Culture  Faith     Gold  Science
X
1            0.0    0.0      5.0      0.0
2            1.0    NaN      NaN      3.0
3            NaN    NaN     10.0      NaN
4            NaN    NaN     15.0      NaN
5            NaN    NaN     20.0      NaN
..           ...    ...      ...      ...
126        592.0    NaN  23122.0   1062.0
127          NaN    NaN  24881.0    964.0
128          NaN    NaN  26438.0    951.0
129        590.0   39.0  29510.0    988.0
130          NaN    NaN      NaN      NaN

[130 rows x 4 columns]

In [7]:
leader = df.at[0, 'LeaderName']
civ = df.at[0, 'CivilizationName']

In [8]:
p.assign(LeaderName=leader, CivilizationName=civ)

DataSet  Culture  Faith     Gold  Science        LeaderName CivilizationName
X
1            0.0    0.0      5.0      0.0  Robert the Bruce         Scotland
2            1.0    NaN      NaN      3.0  Robert the Bruce         Scotland
3            NaN    NaN     10.0      NaN  Robert the Bruce         Scotland
4            NaN    NaN     15.0      NaN  Robert the Bruce         Scotland
5            NaN    NaN     20.0      NaN  Robert the Bruce         Scotland
..           ...    ...      ...      ...               ...              ...
126        592.0    NaN  23122.0   1062.0  Robert the Bruce         Scotland
127          NaN    NaN  24881.0    964.0  Robert the Bruce         Scotland
128          NaN    NaN  26438.0    951.0  Robert the Bruce         Scotland
129        590.0   39.0  29510.0    988.0  Robert the Bruce         Scotland
130          NaN    NaN      NaN      NaN  Robert the Bruce         Scotland

[130 rows x 6 columns]

In [9]:
dfs = []
for player_id in df['PlayerObjectId'].values:
    temp = df[df['PlayerObjectId'] == player_id]
    temp = temp.reset_index()
    game_id = temp.at[0, 'GameId']
    temp = pivot_table(temp)
    temp = temp.assign(PlayerObjectId=player_id, GameId=game_id)
    dfs.append(temp)
total = pd.concat(dfs, axis=0)
total.head()

KeyboardInterrupt:

In [63]:
total.to_sql('yields', conn, if_exists='replace')

987817

In [34]:
df = pd.read_sql_query('SELECT * FROM Yields', conn)
# df = df.rename({'Civilization': 'CivilizationName', 'Leader': 'LeaderName', 'Turn': 'X', 'Value': 'Y'}, axis=1)
df.head()

,ObjectId,GameId,PlayerObjectId,Type,Name,DataSetId,DataSet,Turn,Value,Civilization,Leader
0,1,1,1,Player,None,7,BarbarianCampsCleared,1,0.0,Scotland,Robert the Bruce
1,1,1,1,Player,None,7,BarbarianCampsCleared,12,1.0,Scotland,Robert the Bruce
2,1,1,1,Player,None,7,BarbarianCampsCleared,16,2.0,Scotland,Robert the Bruce
3,1,1,1,Player,None,7,BarbarianCampsCleared,34,3.0,Scotland,Robert the Bruce
4,1,1,1,Player,None,7,BarbarianCampsCleared,39,4.0,Scotland,Robert the Bruce

In [62]:
dfs = []
for object_id in tqdm(df['ObjectId'].unique()):
    for game_id in df['GameId'].unique():
        temp = df[(df['ObjectId'] == object_id) &
                  (df['GameId'] == game_id)]
        if temp.shape[0] == 0:
            continue
        temp = temp.reset_index()
        player_id = temp.at[0, 'PlayerObjectId']
        type = temp.at[0, 'Type']
        name = temp.at[0, 'Name']
        civ = temp.at[0, 'Civilization']
        leader = temp.at[0, 'Leader']
        p = temp.pivot(index='Turn', columns='DataSet', values='Value')
        p = p.assign(PlayerObjectId=player_id, 
                        GameId=game_id,
                        Type=type,
                        Name=name,
                        Civilization=civ,
                        Leader=leader)
        dfs.append(p)
total = pd.concat(dfs, axis=0)
total.head()

100%|██████████| 307/307 [00:02<00:00, 137.55it/s]

DataSet,BarbarianCampsCleared,BarbariansKilled,BuildingsConstructed,CO2,CitiesFounded,CivicsAcquired,Combats,Culture,DiploVP,DistrictsConstructed,...,CitiesConquered,CitiesRazed,CitiesLost,Food,Population,Production,Tourism,Beliefs,Cities,Followers
Turn,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,1.0,0.0,1.0,0.0,NaN,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
print(total.shape)
[print(x) for x in total.columns]

(14101, 41)
BarbarianCampsCleared
BarbariansKilled
BuildingsConstructed
CO2
CitiesFounded
CivicsAcquired
Combats
Culture
DiploVP
DistrictsConstructed
Faith
Favor
Gold
GoodyHutsPopped
GreatPeopleEarned
NaturalWondersDiscovered
Science
ScienceVP
Score
TechsAcquired
UnitsKilled
UnitsLost
WondersConstructed
PlayerObjectId
GameId
Type
Name
Civilization
Leader
WarsDeclared
WarsReceived
CitiesConquered
CitiesRazed
CitiesLost
Food
Population
Production
Tourism
Beliefs
Cities
Followers

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [44]:
game = total[total['GameId'] == 1]
game.index.value_counts()

Turn
130    66
116    52
115    51
114    50
125    50
       ..
5       8
7       6
4       6
3       6
1       6
Name: count, Length: 130, dtype: int64

In [26]:
p = temp.pivot(index='X', columns='DataSet', values='Y')
p

DataSet,BarbarianCampsCleared,BarbariansKilled,BuildingsConstructed,CO2,CitiesFounded,CivicsAcquired,Combats,Culture,DiploVP,DistrictsConstructed,...,GoodyHutsPopped,GreatPeopleEarned,NaturalWondersDiscovered,Science,ScienceVP,Score,TechsAcquired,UnitsKilled,UnitsLost,WondersConstructed
X,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,1.0,0.0,1.0,0.0,NaN,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,5.0,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,NaN,NaN,1.0,2530.0,NaN,NaN,3.0,592.0,NaN,NaN,...,NaN,NaN,NaN,1062.0,5.0,1188.0,NaN,1.0,NaN,NaN
127,NaN,43.0,6.0,2582.0,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,964.0,6.0,1194.0,74.0,2.0,NaN,NaN
128,NaN,45.0,NaN,2635.0,NaN,50.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,951.0,7.0,1202.0,75.0,NaN,NaN,NaN
129,NaN,NaN,NaN,2730.0,NaN,NaN,NaN,590.0,NaN,NaN,...,NaN,NaN,NaN,988.0,14.0,1206.0,NaN,NaN,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
p.index.name

'X'

In [63]:
l = total.columns.tolist()
l.remove('Leader')
l.remove('Civilization')
l.remove('Type')
l

['BarbarianCampsCleared',
 'BarbariansKilled',
 'BuildingsConstructed',
 'CO2',
 'CitiesFounded',
 'CivicsAcquired',
 'Combats',
 'Culture',
 'DiploVP',
 'DistrictsConstructed',
 'Faith',
 'Favor',
 'Gold',
 'GoodyHutsPopped',
 'GreatPeopleEarned',
 'NaturalWondersDiscovered',
 'Science',
 'ScienceVP',
 'Score',
 'TechsAcquired',
 'UnitsKilled',
 'UnitsLost',
 'WondersConstructed',
 'PlayerObjectId',
 'GameId',
 'Name',
 'WarsDeclared',
 'WarsReceived',
 'CitiesConquered',
 'CitiesRazed',
 'CitiesLost',
 'Food',
 'Population',
 'Production',
 'Tourism',
 'Beliefs',
 'Cities',
 'Followers']

In [64]:
temp = total[['Leader', 'Civilization', 'Type', *l]]
temp.to_sql('YieldsGrouped', conn, if_exists='replace')

14101

In [49]:
test = total.copy()

In [54]:
test = test[['Leader', 'Civilization', *l]]

In [55]:
test.head()

DataSet,Leader,Civilization,BarbarianCampsCleared,BarbariansKilled,BuildingsConstructed,CO2,CitiesFounded,CivicsAcquired,Combats,Culture,...,CitiesConquered,CitiesRazed,CitiesLost,Food,Population,Production,Tourism,Beliefs,Cities,Followers
Turn,,,,,,,,,,,,,,,,,,,,,
1,Robert the Bruce,Scotland,0.0,0.0,1.0,0.0,1.0,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Robert the Bruce,Scotland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Robert the Bruce,Scotland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Robert the Bruce,Scotland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Robert the Bruce,Scotland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN